root: true

env:
  node: true

parserOptions:
  sourceType: 'module'

extends: 'eslint:recommended'

rules:
  indent: [2, 2, { SwitchCase: 1 }]
  linebreak-style: [2, "unix"]
  quotes: [2, "single", "avoid-escape"]
  semi: ["error", "always"]
  space-before-function-paren: [2, "always"]
